name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
        
    # - name: Setup VSTest
    #   uses: darenm/Setup-VSTest@v1

    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: Restore Packages
      run: nuget restore SimpleNetFrame.sln

    - name: Build Solution
      run: |
        pwd
        msbuild.exe SimpleNetFrame.sln /p:platform="Any CPU" /p:configuration="Release" /p:OutputPath=.\build-output

    # - run: |
    #     dir D:\a\dotnet-framework-48\dotnet-framework-48\SimpleNetFrame\build-output\

    # - run: |
    #     dir D:\a\dotnet-framework-48\dotnet-framework-48\SimpleNetFrame\
        
    # - name: Run Tests
    #   run: vstest.console.exe .\UnitTestProject1\bin\Release\UnitTestProject1.dll

    # - name: Deploy to Azure Web App
    #   id: deploy-to-webapp
    #   uses: azure/webapps-deploy@v2
    #   with:
    #     app-name: 'app-appspoke-az-ince-dev-001'
    #     slot-name: 'Production'
    #     publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_PRODUCTION }}
    #     package: D:\a\dotnet-framework-48\dotnet-framework-48\SimpleNetFrame\build-output\

  deploy:
    needs: build
    runs-on: self-hosted:zone1