name: DAST

on:
  repository_dispatch:
    types: [dast-man-net48-repository-dispatch]

env:
  SIT_SITE: "http://man-net48-sit.azurewebsites.net/"

jobs:
  zap_scan:
    runs-on: ubuntu-20.04
    name: Scan the web application with DAST
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.git_reference }}

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: ${{ env.SIT_SITE }}
          rules_file_name: '.zap/rules.tsv'
          fail_action: true

  # repository_dispatch:
  #   name: Repository dispatch
  #   needs: zap_scan

  #   uses: kubeopsskills-enterprise/ais-share-pipeline/.github/workflows/repository-dispatch.yml@main
  #   with:
  #     REPOSITORY: 'kubeopsskills-enterprise/man-ng-pipeline'
  #     EVENT_TYPE: 'integration-test-ais-ng-repository-dispatch'
  #     SHA: ${{ github.event.client_payload.github_sha }}
  #   secrets:
  #     PAT : ${{ secrets.ORG_PAT  }}